# Generated by Django 3.2.8 on 2021-11-01 14:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peaccmiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tweets_sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=120)),
                ('total_count', models.IntegerField()),
                ('postive_count', models.IntegerField()),
                ('negative_count', models.IntegerField()),
                ('postive_tweets', jsonfield.fields.JSONField()),
                ('negative_tweets', jsonfield.fields.JSONField()),
                ('charts_graph', models.ImageField(blank=True, upload_to='')),
                ('line_graph', models.ImageField(blank=True, upload_to='')),
                ('pie_graph', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tweets_sentiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
