# Generated by Django 3.2.8 on 2021-12-13 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterNLP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userIpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 13, 17, 56, 55, 492078, tzinfo=utc))),
                ('ip_address', models.CharField(max_length=20)),
                ('number_of_requests', models.IntegerField(blank=True, default=1)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='peaccmiddle',
        ),
        migrations.DeleteModel(
            name='tweets_sentiments',
        ),
    ]
