# Generated by Django 3.2.8 on 2021-12-13 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterNLP', '0002_auto_20211213_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useripaddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
