# Generated by Django 3.2.8 on 2022-03-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterNLP', '0003_alter_useripaddress_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets_sentiment',
            name='line_graph',
        ),
    ]
