# Generated by Django 3.2.8 on 2022-03-16 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterNLP', '0004_remove_tweets_sentiment_line_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets_sentiment',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useripaddress',
            name='expiration_date',
            field=models.DateTimeField(default=None),
        ),
    ]
